name: Get YouTube Live m3u8

on:
  schedule:
    - cron: '0 0/3 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-m3u8:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Setup yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Update ma-03-digital.m3u8
      run: |
        mkdir -p ./Sports
        yt_url=$(yt-dlp --print urls https://www.youtube.com/channel/UCRN5ho3UGhUi7ZCBe2G2f2w/live)
        cat > ./Sports/ma-03-digital.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=3689000,CODECS="avc1.100.31,mp4a.40.2",RESOLUTION=1920x1080
        ${yt_url}
        https://raw.githubusercontent.com/MassinDV/videos/main/morocco/ma-03-digital.m3u8
        EOL

    - name: Update natgeo.m3u8
      run: |
        mkdir -p ./Documentaries
        yt_url=$(yt-dlp --print urls https://www.youtube.com/channel/UCpVm7bg6pXKo1Pr6k5kxG9A/live)
        cat > ./Documentaries/natgeo.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:BANDWIDTH=3689000,CODECS="avc1.100.31,mp4a.40.2",RESOLUTION=1920x1080
        ${yt_url}
        https://raw.githubusercontent.com/MassinDV/videos/main/doc/national-geographic.m3u8
        EOL

    - name: Commit and Push Changes
      run: |
        git add -A
        git commit -m "Updated m3u8 links"
        git push
