name: Get YouTube Live m3u8
on:
  schedule:
    - cron: '0 0/3 * * *'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get YouTube Live m3u8
      run: |
        touch ./flashback.m3u8
        yt-dlp --print-urls https://www.youtube.com/channel/UCU6kl_-xHJ0KKKk2CgVixlA/live >> ./flashback.m3u8

        touch ./halabel3eyal.m3u8
        yt-dlp --print-urls https://www.youtube.com/channel/UCC_xW57yJDW-SiMwa7WzJxA/live >> ./halabel3eyal.m3u8

        # Add more channels here following the same pattern

    - name: Commit and Push Changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add .
        git commit -m "Update m3u8 files"
        git push
